/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimsListRouteImport } from './routes/claims.list'
import { Route as ClaimsNewRouteImport } from './routes/claims.new'
import { Route as ClaimsNewSettlementRouteImport } from './routes/claims.new_.settlement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsListRoute = ClaimsListRouteImport.update({
  id: '/claims/list',
  path: '/claims/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsNewRoute = ClaimsNewRouteImport.update({
  id: '/claims/new',
  path: '/claims/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsNewSettlementRoute = ClaimsNewSettlementRouteImport.update({
  id: '/claims/new_/settlement',
  path: '/claims/new/settlement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claims/list': typeof ClaimsListRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims/new/settlement': typeof ClaimsNewSettlementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claims/list': typeof ClaimsListRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims/new/settlement': typeof ClaimsNewSettlementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claims/list': typeof ClaimsListRoute
  '/claims/new': typeof ClaimsNewRoute
  '/claims/new_/settlement': typeof ClaimsNewSettlementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/claims/list' | '/claims/new' | '/claims/new/settlement'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claims/list' | '/claims/new' | '/claims/new/settlement'
  id:
    | '__root__'
    | '/'
    | '/claims/list'
    | '/claims/new'
    | '/claims/new_/settlement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimsListRoute: typeof ClaimsListRoute
  ClaimsNewRoute: typeof ClaimsNewRoute
  ClaimsNewSettlementRoute: typeof ClaimsNewSettlementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/list': {
      id: '/claims/list'
      path: '/claims/list'
      fullPath: '/claims/list'
      preLoaderRoute: typeof ClaimsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/new': {
      id: '/claims/new'
      path: '/claims/new'
      fullPath: '/claims/new'
      preLoaderRoute: typeof ClaimsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/new_/settlement': {
      id: '/claims/new_/settlement'
      path: '/claims/new/settlement'
      fullPath: '/claims/new/settlement'
      preLoaderRoute: typeof ClaimsNewSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimsListRoute: ClaimsListRoute,
  ClaimsNewRoute: ClaimsNewRoute,
  ClaimsNewSettlementRoute: ClaimsNewSettlementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
